export const RolePermissions = {
  SystemAdmin: [
    "accessRequests.CanApproveReject",
    "accessRequests.CanRevoke",
    "systems.CanManage",
    "departments.CanManage",
    "locations.CanManage",
    "docsCategories.CanManageAll",
    "docsCategories.CanManageOwn",
    "docs.CanCreateAll",
    "docs.CanEditAll",
    "docs.CanViewAll",
    "docs.CanArchiveAll",
    "docs.CanCreateOwnDepartment",
    "docs.CanEditOwnDepartment",
    "docs.CanArchiveOwn",
    "docs.CanViewOwnDepartment",
  ],
  HR: [
    "users.CanRegister",
    "users.CanTerminate",
    "users.CanEdit",
    "docs.CanViewOwnDepartment",
  ],
  DepartmentManager: [
    "users.CanView",
    "accessAssignments.CanView",
    "accessRequests.CanView",
    "accessRequests.CanCreate",
    "docsCategories.CanManageOwn",
    "docs.CanCreateOwnDepartment",
    "docs.CanEditOwnDepartment",
    "docs.CanArchiveOwn",
    "docs.CanViewOwnDepartment",
  ],
  DepartmentSupervisor: [
    "docs.CanCreateOwnDepartment",
    "docs.CanEditOwnDepartment",
    "docs.CanArchiveOwn",
    "docs.CanViewOwnDepartment",
  ],
  User: ["docs.CanViewOwnDepartment"],
};
