export const RolePermissions = {
  SystemAdmin: [
    "systems.CanManage",
    "departments.CanManage",
    "locations.CanManage",
    "accessRequests.CanViewCreate",
    "docsCategories.CanManage",
    "docs.CanEdit",
    "docs.CanView",
    "users.CanView",
    "users.CanEdit",
    "users.CanRegister",
    "users.CanTerminate",
  ],
  HumanResources: [
    "users.CanRegister",
    "users.CanEdit",
    "users.CanTerminate",
    "users.CanView",
    "docs.CanView",
  ],
  Manager: [
    "users.CanView",
    "accessRequests.CanViewCreate",
    "docsCategories.CanManage",
    "docs.CanEdit",
    "docs.CanView",
  ],
  Supervisor: ["docs.CanEdit", "docs.CanView"],
  User: ["docs.CanView"],
};
